name: scanner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^0.4.0
  image_picker: ^0.8.4+4
  zxing2: ^0.2.3
  image: ^3.0.1
  device_preview: ^1.2.0
  url_launcher: ^6.0.9


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
